---
title: "2026 Cowichan River Dashboard Test"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(plotly)
```

Column {data-width=800}
-----------------------------------------------------------------------

### DO Skutz Fall 

```{r}
# Formatting DO Skutz fall data
DOSkutzData <- read.csv("https://raw.githubusercontent.com/caitlynboconnor/2026CVRDWaterData/refs/heads/main/DO%20Skutz%202026-04-28%2015_26_52%20PDT.csv")
DOSkutzData <- DOSkutzData[-c(1),-c(1,6:9)]
DOSkutzData$Site <- "Skutz Falls - Remote (km32)"
DOSkutzData$Date.Time..PDT. <- as.POSIXct(DOSkutzData$Date.Time..PDT., format = "%m/%d/%Y %H:%M")

# Plotting DO Skutz ggplot  
DOSkutzPlot <- ggplot(data = DOSkutzData, aes(x=Date.Time..PDT., y=Measured.DO....mg.L..W.DO.22225580.)) +
  geom_line(colour = "#800074") + geom_point(colour = "#800074") + 
  scale_x_datetime(date_labels= "%e-%b", date_breaks="1 day")+ 
  theme_classic() + 
  theme(panel.grid.major.y = element_line(colour = "gray", size = 0.5, linetype = 2)) +
  xlab("") + ylab("Measured DO") + ggtitle("Skutz Falls")

ggplotly(DOSkutzPlot)
```

-----------------------------------------------------------------------

### PH Skutz Fall

```{r}
# Formatting PH Skutz fall data
pHSkutzData <- read.csv("https://raw.githubusercontent.com/caitlynboconnor/2026CVRDWaterData/refs/heads/main/pH%20Skutz%202026-04-28%2015_28_21%20PDT.csv")
pHSkutzData <- pHSkutzData[-c(1:50), -c(1,6:8)]
pHSkutzData$Site <- "Skutz Falls - Remote (km 32)"
pHSkutzData$DateTime <- as.POSIXct(pHSkutzData$DateTime, format = "%m/%d/%Y %H:%M") 

# Plotting PH Skutz ggplot basic
pHSkutzPlot <- ggplot(data = pHSkutzData, aes(x=DateTime, y=pH)) +
  geom_line(colour = "#298c8c") + geom_point(colour = "#298c8c") +
  scale_x_datetime(date_labels= "%e-%b", date_breaks="1 day")+ 
  theme_classic() + 
  theme(panel.grid.major.y = element_line(colour = "gray", size = 0.5, linetype = 2)) +
  xlab("") + ylab("pH") + ggtitle("Skutz Falls") 

ggplotly(pHSkutzPlot)
```

### Chart C

```{r}
#Temperature Formatting Data using DO temps

TempSkutzData <- read.csv("https://raw.githubusercontent.com/caitlynboconnor/2026CVRDWaterData/refs/heads/main/DO%20Skutz%202026-04-28%2015_26_52%20PDT.csv")
TempSkutzData <- TempSkutzData[-c(1), -c(1,6:9)]
TempSkutzData$Site <- "Skutz Falls - Remote (km32)"
TempSkutzData$Date.Time..PDT. <- as.POSIXct(TempSkutzData$Date.Time..PDT., format = "%m/%d/%Y %H:%M")

#Temperature plotting

TempSkutzPlot <- ggplot(data = TempSkutzData, aes(x=Date.Time..PDT., y=Measured.DO....mg.L..W.DO.22225580.)) +
  geom_line(colour = "#f1a226") + geom_point(colour = "#f1a226") + 
  scale_x_datetime(date_labels= "%e-%b", date_breaks="1 day")+ 
  theme_classic() + 
  theme(panel.grid.major.y = element_line(colour = "gray", size = 0.5, linetype = 2)) +
  xlab("") + ylab("Temperature") + ggtitle("Skutz Falls")

ggplotly(TempSkutzPlot)


```

